<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:output method="html" encoding="UTF-8"/>
  <xsl:template match="/">
    <html>
      <head>
        <title>HTML Sitemap</title>
        <style>
          body {
            font-family: 'Segoe UI', Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
          }
          header {
            background-color: #0078D7;
            color: white;
            padding: 20px;
            text-align: center;
          }
          header h1 {
            margin: 0;
          }
          main {
            padding: 20px;
            max-width: 1200px;
            margin: 0 auto;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            background-color: white;
          }
          th, td {
            border: 1px solid #e0e0e0;
            padding: 10px;
            text-align: left;
          }
          th {
            background-color: #0078D7;
            color: white;
            font-weight: bold;
          }
          td a {
            color: #0078D7;
            text-decoration: none;
          }
          td a:hover {
            text-decoration: underline;
          }
          footer {
            text-align: center;
            margin-top: 30px;
            padding: 10px 0;
            background-color: #0078D7;
            color: white;
            font-size: 0.9em;
          }
          footer p {
            margin: 5px 0;
          }
        </style>
      </head>
      <body>
        <header>
          <h1>XML Sitemap for kamrul.us</h1>
          <p>Explore all indexed URLs in a user-friendly format.</p>
        </header>
        <main>
          <table>
            <thead>
              <tr>
                <th>URL</th>
                <th>Last Modified</th>
                <th>Change Frequency</th>
                <th>Priority</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="urlset/url">
                <tr>
                  <td><a href="{loc}" target="_blank"><xsl:value-of select="loc"/></a></td>
                  <td><xsl:value-of select="lastmod"/></td>
                  <td><xsl:value-of select="changefreq"/></td>
                  <td><xsl:value-of select="priority"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </main>
        <footer>
          <p>Generated by Kamrul</p>
          <p>Copyright © 2025 Kamrul. All rights reserved.</p>
        </footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
