<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:output method="html" encoding="UTF-8"/>
  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap for kamrul.us</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
          }
          header {
            background-color: #0078D7;
            color: #fff;
            text-align: center;
            padding: 20px;
          }
          table {
            margin: 20px auto;
            border-collapse: collapse;
            width: 90%;
            background: white;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
          }
          th, td {
            border: 1px solid #ddd;
            text-align: left;
            padding: 8px;
          }
          th {
            background-color: #0078D7;
            color: white;
          }
          a {
            color: #0078D7;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          footer {
            text-align: center;
            margin-top: 20px;
            padding: 10px;
            background-color: #0078D7;
            color: white;
          }
        </style>
      </head>
      <body>
        <header>
          <h1>XML Sitemap for kamrul.us</h1>
          <p>Explore all indexed URLs in a user-friendly format.</p>
        </header>
        <table>
          <thead>
            <tr>
              <th>URL</th>
              <th>Last Modified</th>
              <th>Change Frequency</th>
              <th>Priority</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="urlset/url">
              <tr>
                <td><a href="{loc}" target="_blank"><xsl:value-of select="loc"/></a></td>
                <td><xsl:value-of select="lastmod"/></td>
                <td><xsl:value-of select="changefreq"/></td>
                <td><xsl:value-of select="priority"/></td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
        <footer>
          <p>Generated by Kamrul</p>
          <p>Copyright © 2025 Kamrul. All rights reserved.</p>
        </footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
