<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap for kamrul.us</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            background: linear-gradient(to right, #0078D7, #0053A6);
            color: #333;
            margin: 0;
            padding: 0;
          }
          .container {
            margin: 40px auto;
            max-width: 1000px;
            background: #fff;
            padding: 20px;
            border-radius: 12px;
            box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.2);
          }
          header {
            text-align: center;
            padding: 20px;
            background: #0078D7;
            color: white;
            border-radius: 12px 12px 0 0;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th, td {
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
          }
          th {
            background: #0078D7;
            color: white;
          }
          tr:nth-child(even) {
            background: #f9f9f9;
          }
          a {
            color: #0078D7;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          footer {
            text-align: center;
            margin-top: 20px;
            color: #777;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <header>
            <h1>XML Sitemap for kamrul.us</h1>
            <p>Explore all indexed URLs in a user-friendly format.</p>
          </header>
          <table>
            <tr>
              <th>URL</th>
              <th>Last Modified</th>
              <th>Change Frequency</th>
              <th>Priority</th>
            </tr>
            <xsl:for-each select="urlset/url">
              <tr>
                <td><a href="{loc}"><xsl:value-of select="loc" /></a></td>
                <td><xsl:value-of select="lastmod" /></td>
                <td><xsl:value-of select="changefreq" /></td>
                <td><xsl:value-of select="priority" /></td>
              </tr>
            </xsl:for-each>
          </table>
          <footer>
            <p>Generated by Kamrul</p>
            <p>Copyright © 2025 Kamrul. All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
